language: python
python:
- '3.4'
before_script:
    flake8 .
script: 
- coverage run tests/dummyTest.py
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: AUgJ7Abd/zW3W5yc3o3IA5M6J+/i4H4fdkrfWHmLS24m7hlfTvtuuKYmhvjYsOHUKe1aK97NpArcBx4Uao7F4KVoHvTUwKIaCBILmllQaWVKrKoX27Xo0neLemp+gtZvmGLJlLDrQa1HF8l5zJLk5nsZ8to9tl4zI3XXSLROxj024ZdBVf3pf9rvAhXpZnioLqepJAdk27MA0CwFTfy3pW84vC/A+9frB7OnOOqfysBsYfhG7/LXFavmBAp7I9RJE/toQiTax2W7whUNgIXoSgATzFLFENqjVFr14yQJ5cGsWcbXmpKmtRe38ShThT1RihMpgUnBFHX2H0I2q1GJBtQ2xnueI7Q7JvWokCn4mG/xvC5qtMsVXNMxbwYUap3SJdtHnP16UHFaRBsrhs/+XuUZRPKF1cI13tOFsdBa5jUxNr0XqUvXeZIG2lj1/gaGIdxUkJnUTVKXme1XqU0EPoaVOmDr45gISy8kUYbqK+Dhj3uJmPhP0brMA8beQUsPR5Q3L+9119Vrq0OPCg0s5CnaDGFiVjODvRKk6jvTtDkYA4lhbUXvWon+gQpplfGpZ4YrlflP4ma32/e0jxesgscGEoTNjSUC49QrBU+fbdP3JdR7zKaFGptMV3fC5ILYFPn/absokwoU9TJmbIAnBaChJw8plZXcPEubsjyCi6A=
  app: github-api-team9
  on:
    repo: glo2003/team9
