language: python
python:
- '3.2'
- '3.3'
- '3.4'
- '3.5'
before_script:
- chmod +x ./tests/dummyTest.py

script: "./tests/dummyTest.py"

deploy:
  provider: Heroku
  api_key:
    secure: VNXjL9BsX5fvpl1ZKJyCDs4Y292CbXKW44doHBF5Qjgnc5OvkxWgF8vCSCN4Jv/RPohQq48OF4Yk6IzJyuQKqJ/WvXO1DLQ875ftgXVhXBRWo0Qo8MrBQq1HESB6Sulb86AKITiJE6Sb46KxpZJoGqeOvyrPUrHlYIPGf3mf4Sl/OMUo1C8P3b0V2oztak5MkFDeUzSfqXNKv95iNmxGt6CMMv8yROIEs1LVOuQySSlATHqZPMshZu4iYffFtuj/eIhy0eFKJpldVbgeDwuJJDQ6+W+CDCWvArWs0RzA9wCT1oEAnOJiESPpheU7bvUNJ++5dHWtWB+93w43IVPLjcPSS5o9SNcIzH8+84TWQ3dlamHhHb2A681SDIS63G8FbXfyUTIW9tgwHZ08Mh9/EotJkNuu8rrG/rZHgDaA70qsDkgqoOY5IjTD+ht35GsAMtqACwaAdzzw07jwvzMVBVmDLkvFwAJUN4m3FCfZ50kUThRxQ5xExUh4SGtl88MGFOviATegtm/GcU4qO43nynMjX+YmR7DiN9n7Jtog0+oDr84u66/54jXag6VUuM22694PC2JClNZYe9+rFzwmIagKJshWUjKRB2Znya6qcvXb8/Xo1fpv5N4RkyzcBhfxsOusPWcf0xQuInJldUohDQnYkly07Gg7T5HR/qy6DTQ=
